{
printParameters         : true,
savePath                : "/home/unnar/catkin_ws/src/rosOgre/run_from/",
cloudPath               : "/home/unnar/catkin_ws/src/Metarooms/room_0/intermediate_cloud0047.pcd",
configPath              : "/home/unnar/catkin_ws/src/rosOgre/dist/bin/",
SVVoxelResolution       : 0.01,
SVSeedResolution        : 0.15,
SVColorImportance       : 20.0,
SVSpatialImportance     : 0.5,
RANSACDistanceThreshold : 0.02,
RANSACMinInliers        : 1000,
VoxelLeafSize           : 0.005,
GP3SearchRad            : 0.25,
GP3Mu                   : 4.5,
GP3MaxNearestNeighbours : 20,
GP3Ksearch              : 20,
RWHullMaxDist           : 0.01,
simplifyHulls           : true,
}