{
printParameters         : true,
savePath                : "/home/unnar/catkin_ws/src/rosOgre/run_from/",
#cloudPath               : "/home/unnar/catkin_ws/src/Metarooms/room_2/intermediate_cloud0043.pcd",
cloudPath               : "/home/unnar/catkin_ws/src/Metarooms/room_0/intermediate_cloud0011.pcd",
configPath              : "/home/unnar/catkin_ws/src/rosOgre/dist/bin/",
SVVoxelResolution       : 0.01,
SVSeedResolution        : 0.03,
SVColorImportance       : 0.1,
SVSpatialImportance     : 5.0,
RANSACDistanceThreshold : 0.08,
RANSACMinInliers        : 200,
VoxelLeafSize           : 0.01,
GP3SearchRad            : 0.09,
GP3Mu                   : 4.5,
GP3MaxNearestNeighbours : 20,
GP3Ksearch              : 8,
RWHullMaxDist           : 0.01,
ECMinClusterSize        : 10,
ECClusterTolerance      : 0.04,
simplifyHulls           : true,
}