{
printParameters         : true,
savePath                : "/home/unnar/catkin_ws/src/rosOgre/run_from/",
#cloudPath               : "/home/unnar/catkin_ws/src/Metarooms/room_0/intermediate_cloud0044.pcd",
cloudPath               : "/home/unnar/catkin_ws/src/rosOgre/run_from/final_cloud.pcd",
configPath              : "/home/unnar/catkin_ws/src/rosOgre/dist/bin/",
SVVoxelResolution       : 0.01,
SVSeedResolution        : 0.05,
SVColorImportance       : 5.0,
SVSpatialImportance     : 1.0,
RANSACDistanceThreshold : 0.04,
RANSACMinInliers        : 1000,
VoxelLeafSize           : 0.01,
GP3SearchRad            : 0.15,
GP3Mu                   : 4.5,
GP3MaxNearestNeighbours : 20,
GP3Ksearch              : 20,
RWHullMaxDist           : 0.01,
simplifyHulls           : true,
}